name: Welcome workflow

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest

    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thanks for opening your first issue!"
          pr-message: "Thanks for opening this pull request!"
